#!/bin/bash

LOCK_FILE="$HOME/.cache/eww-music.lock"
EWW_BIN="$HOME/.local/bin/eww/eww"

if [[ ! -f "$LOCK_FILE" ]]; then
    touch "$LOCK_FILE"
    eww -c $HOME/.config/eww/music/ open music 
    $HOME/.config/eww/bar/scripts/open.py
else
    rm "$LOCK_FILE"
    eww -c $HOME/.config/eww/music/ close music 
    $HOME/.config/eww/bar/scripts/close.py
fi
