#!/bin/sh

#####################################################
#   ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗   #
#   ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║   #
#   ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║   #
#   ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║   #
#   ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║   #
#   ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝   #                                    
################### By: Corro-Kun  ##################

# ################################################### #
# #                   WINDOW RULES                  # #
# ################################################### #

bspc monitor -d 1 2 3 4 5

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule viewnior  state=floating

# ################################################### #
# #                    STARTS APPS                  # #
# ################################################### #

# Run sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Run power manager.
xfce4-power-manager &

# Run notification daemon.
dunst &

# Run Picom.
picom --config ~/.config/bspwm/picom.conf &

# Run Bar.
eww -c ~/.config/eww/bar --restart open bar &

feh --bg-scale $HOME/.config/bspwm/fondo.png &

# wallpaper
exec ~/.config/video-wallpapers/setwall 1 &

sleep 2

dunstify -i $HOME/.config/bspwm/welcome.png "Comencemos nuestra historia juntos..." &

paplay $HOME/.config/bspwm/sounds/welcome.ogg &

sleep 2


# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

bspc subscribe node_state | while read -r _ _ _ _ state flag; do
    if [ "$state" != "fullscreen" ]; then
        continue
    fi
    if [ "$flag" == on ]; then
        eww -c ~/.config/eww/bar --restart close-all
  else
        eww -c ~/.config/eww/bar --restart open bar
    fi
done &

bspc config left_padding        64 

bspc config border_width         2
bspc config window_gap          15
bspc config split_ratio          0.50

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config normal_border_color "#FCE8DA"
bspc config focused_border_color "#E3C99F"

#windows_count=$(bspc query -N -d focused | wc -l) 

#if [ "$windows_count" -eq 1 ]; then
#    bspc config focused_border_color "#414141"
#else
#    bspc config focused_border_color "#e2e2e2"
#fi
