#!/bin/python3
import subprocess

def main():
    subprocess.run("paplay $HOME/.config/bspwm/sounds/block.ogg &",shell=True)
    subprocess.run("betterlockscreen --lock",shell=True)

if __name__ == "__main__":
    main()
